name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]  # Déclenchement quand on pousse sur "main"
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # Permet de déclencher manuellement via GitHub Actions UI

jobs:
  build:
    runs-on: ubuntu-latest  # Utiliser un serveur GitHub

    environment: Docker  # Utilisation de l’environnement Docker pour récupérer les secrets

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Récupère le code du repo

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Utilise Docker Buildx pour optimiser le build

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and Push Docker Image with WAN
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            aleou/runpod-worker-comfy:wan2.1
            aleou/runpod-worker-comfy:latest
          cache-from: type=registry,ref=aleou/runpod-worker-comfy:latest
          cache-to: type=inline
          build-args: |
            MODEL_TYPE=Wan
